---
name: CI
on: [push, pull_request]

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: "8.10.7"
          cabal-version: "3.6.2.0"
      - name: Install SDL2
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev
      - name: Run tests
        run: cabal new-test
